server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/postgres"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
      
